import type { Metadata } from 'next'
import '../globals.css'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'videoplatform',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-500 font-poppins text-white">
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  )
}
